### ISSUE TITLE
missing submodule commit for libsquish

### ISSUE THREAD

**Issue by dvessel** [akb825/Cuttlefish#15]
>❯ git pull --recurse-submodules
Fetching submodule lib/FreeImage
Fetching submodule lib/ISPCTextureCompressor
Fetching submodule lib/PVRTexToolLib
Fetching submodule lib/astc-encoder
Fetching submodule lib/astc-encoder/Source/GoogleTest
Fetching submodule lib/bc7enc_rdo
Fetching submodule lib/compressonator
Fetching submodule lib/etc2comp
Fetching submodule lib/glm
Fetching submodule lib/libsquish
Already up to date.
fatal: remote error: upload-pack: not our ref a9087786ced42a1a4ee137c1ad5bf197dd2d6b72
fatal: Fetched in submodule path 'lib/libsquish', but it did not contain a9087786ced42a1a4ee137c1ad5bf197dd2d6b72. Direct fetching of that commit failed.

`a9087786ced42a1a4ee137c1ad5bf197dd2d6b72` is missing. It looks like libsquish over on github has no history. Only 5 commits.

> fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [lib/CMakeFiles/cuttlefish_lib.dir/libsquish/squish.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/cuttlefish_lib.dir/all] Error 2
make: *** [all] Error 2

Fails while building.

**Comment by akb825** [comment]
Run `git submodule sync` to make sure the submodule URLs are up to date. You may need to do a pull without recursing submodules first to ensure that it updates the base repository so it can see the new submodule URLs.
