### ISSUE TITLE
error: file format DDS doesn't support format A8B8G8R8 with type (*insert any*)

### ISSUE THREAD

**Issue by BigheadSMZ** [akb825/Cuttlefish#21]
Currently it seems impossible to actually create certain types of DDS textures. Uncompressed format "A8B8G8R8" will always fail because of the error message in the title of this issue. It doesn't matter what is selected as the type: unorm, snorm, uint, int, ufloat, or float. The tool itself will also always try to use the default "unorm" type if the "--type" command is omitted completely, so the error message is always present.

Figured I'd also provide a bit more context. I am on Windows 11, using the x64 version of cuttlefish.exe. The command I am attempting can be the most basic possible using only (--input in.png --format A8B8G8R8 --output out.dds) and the error message above will still be triggered.

Edit: Ok this issue may be invalid, maybe I'm misunderstanding the type. I got A8B8G8R8 mixed up with B8G8R8A8 (the latter is what I was actually trying to make) and it works. Also, R8G8B8A8 also works. So it is just A8B8G8R8 this is giving the error message. Maybe I'm not understanding how to use that format.

**Comment by akb825** [comment]
DDS textures support the set of texture formats supported by DirectX, which you can check with the documentation of [DXGI_FORMAT](https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format). For the 8 bit per channel formats, it supports RGBA ordering and BGRA ordering, but not ABGR. This is also listed under the "Limitations" section of README.md at the repository root.
