### ISSUE TITLE
--swizzle channel ordering not working as expected.

### ISSUE THREAD

**Issue by alecazam** [akb825/Cuttlefish#4]
I've been trying to swizzle some textures with the following command on macOS, but the channel ordering doesn't look correct.  I looked over the swizzle sources, and it makes sense, so maybe the jpeg/png code is loading in images as rbga instead of rgba.  I wasn't able to debug from the Xcode project, but I'll work on trying to correct it.

This works to get the g and a channels populated with data, but I'm setting ba = gr (confirmed data in PVRTexToolGUI)
cuttlefish --swizzle xxgr -f ASTC_4x4 --srgb -i Image.jpeg -o Image.ktx
cuttlefish --swizzle xxgr -f ASTC_4x4 --srgb -i Image.png -o Image.ktx

Was expecting to use, ga = gr
cuttlefish --swizzle xgxr -f ASTC_4x4 --srgb -i Image.jpeg -o Image.ktx
cuttlefish --swizzle xgxr -f ASTC_4x4 --srgb -i Image.png -o Image.ktx

This should be a noop, but the channels are reordered.
cuttlefish --swizzle rgba -f ASTC_4x4 --srgb -i Image.png -o Image.ktx

Channel info from first swizzle on a Image.jpeg.

![image](https://user-images.githubusercontent.com/3750359/90461464-302d4200-e0bb-11ea-8200-07fcfffce0ce.png)

**Comment by akb825** [comment]
After taking a quick look, the green and blue channels were swapped when parsing the command-line arguments.

**Comment by akb825** [comment]
I pushed up a fix to resolve the incorrect command-line parsing.

**Comment by alecazam** [comment]
This worked great.
