### ISSUE TITLE
PVRTC needs a squarepo2 option

### ISSUE THREAD

**Issue by alecazam** [akb825/Cuttlefish#5]
PVRTexTool has a --square argument for resizing since PVRTC must be square pow2 textures.  Since Cuttlefish supports PVRTC, this would save scripts from having to compute the max(pow2(width), pow2(height)) to pass down for the resize option.  I can do this in the shell/python scripts that I have for now.

--resize squarepo2 squarepo2 cubic

**Comment by akb825** [comment]
Seams reasonable, I can add some additional options for the minimum and maximum between width and height.

**Comment by akb825** [comment]
I've added options for width, height, min, and max, each of which can be decorated with "-nextpo2" and "-nearestpo2". In your example, you'll want `--resize max-nextpo2 max-nextpo2 cubic` (or nearest, depending on which PO2 you prefer).

I'll hold off on creating an official release until the weekend in case you have additional bugs or tweaks you find.

**Comment by alecazam** [comment]
Thanks, that allow PVRTexToolCLI to be completely replaced with cuttlefish.  That's quite the achievement.
